import { Metadata } from "next";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Nextjs-14 application",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "yellow", padding: "1rem" }}>
          <p>My header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "red", padding: "1rem" }}>
          <p>My footer</p>
        </footer>
      </body>
    </html>
  );
}
